# Generated by Django 2.1.3 on 2019-07-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quan',
            name='id_quan',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thanhpho',
            name='id_thanhpho',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='xa',
            name='id_xa',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
