# Generated by Django 2.1.3 on 2019-07-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190720_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
