# Generated by Django 2.1.3 on 2019-07-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userdetail_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='linkTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=255, verbose_name='Name link')),
                ('path', models.TextField(default='', verbose_name='Path Url')),
                ('des', models.CharField(default='', max_length=255, verbose_name='Mô tả')),
                ('device', models.CharField(default='', max_length=255, verbose_name='Thiết bị đăng nhập khi lưu')),
                ('delete_flg', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='userdetail',
            name='device',
            field=models.CharField(default='', max_length=255, verbose_name='Thiết bị đăng nhập khi lưu'),
        ),
    ]
