# Generated by Django 2.1.3 on 2019-07-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190723_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktable',
            name='display_flg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linktable',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
