# Generated by Django 2.1.3 on 2019-07-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190723_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktable',
            name='display_flg',
            field=models.IntegerField(default=2),
        ),
    ]
